College-ERP-master/CollegeERP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('info.urls')),
    path('info/', include('info.urls')),
    path('api/', include('apis.urls')),
    path('announcements/', include('announcements.urls')),
    path('accounts/login/',
         auth_views.LoginView.as_view(template_name='info/login.html'), name='login'),
    path('accounts/logout/',
         auth_views.LogoutView.as_view(template_name='info/logout.html'), name='logout'),
     path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
]

College-ERP-master/apis/urls.py
from django.urls import path, include
import apis.views as api_view
from django.contrib import admin


urlpatterns = [
    path('details/', api_view.DetailView.as_view()),
    path('attendance/', api_view.AttendanceView.as_view()),
    path('marks/', api_view.MarksView.as_view()),
    path('timetable/', api_view.TimetableView.as_view()),
]

College-ERP-master/info/urls.py
from django.urls import path, include
from . import views
from django.contrib import admin
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name='index'),
    path('edit_members',views.edit_members,name='edit_members'),
    path('add_delete_class',views.add_delete_class,name='add_delete_class'),
    path('add_delete_HOD',views.add_delete_HOD,name='add_delete_HOD'),
    path('get_hods',views.get_hods,name='get_hods'),
    path('reset_password/', auth_views.PasswordResetView.as_view(),name="reset_password"),
    path('announce/',views.announce,name='announce'),
    path('presentation',views.presentation,name='presentation'),
    path('student/<slug:stud_id>/attendance/',
         views.attendance, name='attendance'),
    path('student/<slug:stud_id>/<slug:course_id>/attendance/',
         views.attendance_detail, name='attendance_detail'),
    path('student/<slug:class_id>/timetable/',
         views.timetable, name='timetable'),
    # path('student/<slug:class_id>/search/', views.student_search, name='student_search'),

    path('student/<slug:stud_id>/marks_list/',
         views.marks_list, name='marks_list'),

    path('teacher/<slug:teacher_id>/<int:choice>/Classes/',
         views.t_clas, name='t_clas'),
    path('teacher/<int:assign_id>/Students/attendance/',
         views.t_student, name='t_student'),
    path('teacher/<int:assign_id>/ClassDates/',
         views.t_class_date, name='t_class_date'),
    path('teacher/<int:ass_c_id>/Cancel/',
         views.cancel_class, name='cancel_class'),
    path('teacher/<int:ass_c_id>/attendance/',
         views.t_attendance, name='t_attendance'),
    path('teacher/<int:ass_c_id>/Edit_att/', views.edit_att, name='edit_att'),
    path('teacher/<int:ass_c_id>/attendance/confirm/',
         views.confirm, name='confirm'),
    path('teacher/<slug:stud_id>/<slug:course_id>/attendance/',
         views.t_attendance_detail, name='t_attendance_detail'),
    path('teacher/<int:att_id>/change_attendance/',
         views.change_att, name='change_att'),
    path('teacher/<int:assign_id>/Extra_class/',
         views.t_extra_class, name='t_extra_class'),
    path('teacher/<slug:assign_id>/Extra_class/confirm/',
         views.e_confirm, name='e_confirm'),
    path('teacher/<int:assign_id>/Report/', views.t_report, name='t_report'),

    path('teacher/<slug:teacher_id>/t_timetable/',
         views.t_timetable, name='t_timetable'),
    path('teacher/<int:asst_id>/Free_teachers/',
         views.free_teachers, name='free_teachers'),

    path('teacher/<int:assign_id>/marks_list/',
         views.t_marks_list, name='t_marks_list'),
    path('teacher/<int:assign_id>/Students/Marks/',
         views.student_marks, name='t_student_marks'),
    path('teacher/<int:marks_c_id>/marks_entry/',
         views.t_marks_entry, name='t_marks_entry'),
    path('teacher/<int:marks_c_id>/marks_entry/confirm/',
         views.marks_confirm, name='marks_confirm'),
    path('teacher/<int:marks_c_id>/Edit_marks/',
         views.edit_marks, name='edit_marks'),
    path('api/auth/', include('djoser.urls')),
    path('add-teacher/', views.add_teacher, name='add_teacher'),
    path('assign-teacher/', views.assign_teacher, name='assign_teacher'),
    path('get_d_teachers/<str:department_id>/', views.get_d_teachers, name='get_d_teachers'),
    path('get_d_teachers/<str:department_id>/subs', views.get_d_teachers_sub, name='get_d_teachers_sub'),
    path('get_d_teachers/<str:department_id>/classes', views.get_d_teachers_classes, name='get_d_teachers_classes'),
    path('add-student/', views.add_student, name='add_student'),
    path('add_delete_dept/',views.add_delete_dept,name='add_delete_dept')
    
]
admin.site.site_url = None
admin.site.site_header = 'My Site'

College-ERP-master/info/models.py
from django.db import models
import math
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import post_save, post_delete
from datetime import timedelta

# Create your models here.
sex_choice = (
    ('Male', 'Male'),
    ('Female', 'Female')
)


time_slots = (
    ('10:00 - 11:00', '10:00 - 11:00'),
    ('11:00 - 12:00', '11:00 - 12:00'),
    ('12:00 - 01:00', '12:00 - 01:00'),
    ('01:45 - 02:45', '01:45 - 02:45'),
    ('02:45 - 03:30', '02:45 - 03:30'),
    ('03:30 - 04:30', '03:30 - 04:30'),
    ('04:30 - 05:30', '04:30 - 05:30'),
)

DAYS_OF_WEEK = (
    ('Monday', 'Monday'),
    ('Tuesday', 'Tuesday'),
    ('Wednesday', 'Wednesday'),
    ('Thursday', 'Thursday'),
    ('Friday', 'Friday'),
    ('Saturday', 'Saturday'),
)

test_name = (
    ('Class Test 1', 'Class Test 1'),
    ('Midsem Exam', 'Midsem Exam'),
    ('Class Test 2', 'Class Test 2'),
    ('Event 1', 'Event 1'),
    ('Event 2', 'Event 2'),
    ('End Semester Exam', 'End Semester Exam'),
)


class User(AbstractUser):
    @property
    def is_student(self):
        if hasattr(self, 'student'):
            return True
        return False

    @property
    def is_teacher(self):
        if hasattr(self, 'teacher'):
            return True
        return False


class Dept(models.Model):
    id = models.CharField(primary_key='True', max_length=100)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Course(models.Model):
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE)
    id = models.CharField(primary_key='True', max_length=50)
    name = models.CharField(max_length=50)
    shortname = models.CharField(max_length=50, default='X')

    def __str__(self):
        return self.name


class Class(models.Model):
    # courses = models.ManyToManyField(Course, default=1)
    id = models.CharField(primary_key='True', max_length=100)
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE)
    section = models.CharField(max_length=100)
    sem = models.IntegerField()

    class Meta:
        verbose_name_plural = 'classes'

    def __str__(self):
        d = Dept.objects.get(name=self.dept)
        return '%s : %d %s' % (d.name, self.sem, self.section)


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    class_id = models.ForeignKey(Class, on_delete=models.CASCADE, default=1)
    USN = models.CharField(primary_key='True', max_length=100)
    name = models.CharField(max_length=200)
    sex = models.CharField(max_length=50, choices=sex_choice, default='Male')
    DOB = models.DateField(default='1998-01-01')

    def __str__(self):
        return self.name


class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    id = models.CharField(primary_key=True, max_length=100)
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=100)
    sex = models.CharField(max_length=50, choices=sex_choice, default='Male')
    DOB = models.DateField(default='1980-01-01')

    def __str__(self):
        return self.name


class HOD(models.Model):
    id = models.AutoField(primary_key=True)
    hod_id = models.ForeignKey(Teacher,on_delete=models.CASCADE)
    department = models.ForeignKey(Dept, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.hod_id} ({self.department})"

class Assign(models.Model):
    class_id = models.ForeignKey(Class, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('course', 'class_id', 'teacher'),)

    def __str__(self):
        cl = Class.objects.get(id=self.class_id_id)
        cr = Course.objects.get(id=self.course_id)
        te = Teacher.objects.get(id=self.teacher_id)
        return '%s : %s : %s' % (te.name, cr.name, cl)


class AssignTime(models.Model):
    assign = models.ForeignKey(Assign, on_delete=models.CASCADE)
    period = models.CharField(max_length=50, choices=time_slots, default='10:00 - 11:00')
    day = models.CharField(max_length=15, choices=DAYS_OF_WEEK)


class AttendanceClass(models.Model):
    assign = models.ForeignKey(Assign, on_delete=models.CASCADE)
    date = models.DateField()
    status = models.IntegerField(default=0)

    class Meta:
        verbose_name = 'Attendance'
        verbose_name_plural = 'Attendance'


class Attendance(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    attendanceclass = models.ForeignKey(AttendanceClass, on_delete=models.CASCADE, default=1)
    date = models.DateField(default='2018-10-23')
    status = models.BooleanField(default='True')

    def __str__(self):
        sname = Student.objects.get(name=self.student)
        cname = Course.objects.get(name=self.course)
        return '%s : %s' % (sname.name, cname.shortname)


class AttendanceTotal(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('student', 'course'),)

    @property
    def att_class(self):
        stud = Student.objects.get(name=self.student)
        cr = Course.objects.get(name=self.course)
        att_class = Attendance.objects.filter(course=cr, student=stud, status='True').count()
        return att_class

    @property
    def total_class(self):
        stud = Student.objects.get(name=self.student)
        cr = Course.objects.get(name=self.course)
        total_class = Attendance.objects.filter(course=cr, student=stud).count()
        return total_class

    @property
    def attendance(self):
        stud = Student.objects.get(name=self.student)
        cr = Course.objects.get(name=self.course)
        total_class = Attendance.objects.filter(course=cr, student=stud).count()
        att_class = Attendance.objects.filter(course=cr, student=stud, status='True').count()
        if total_class == 0:
            attendance = 0
        else:
            attendance = round(att_class / total_class * 100, 2)
        return attendance

    @property
    def classes_to_attend(self):
        stud = Student.objects.get(name=self.student)
        cr = Course.objects.get(name=self.course)
        total_class = Attendance.objects.filter(course=cr, student=stud).count()
        att_class = Attendance.objects.filter(course=cr, student=stud, status='True').count()
        cta = math.ceil((0.75 * total_class - att_class) / 0.25)
        if cta < 0:
            return 0
        return cta


class StudentCourse(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('student', 'course'),)
        verbose_name_plural = 'Marks'

    def __str__(self):
        sname = Student.objects.get(name=self.student)
        cname = Course.objects.get(name=self.course)
        return '%s : %s' % (sname.name, cname.shortname)

    def get_cie(self):
        marks_list = self.marks_set.all()
        m = []
        for mk in marks_list:
            m.append(mk.marks1)
        cie = math.ceil(sum(m[:5]) / 2)
        return cie

    def get_attendance(self):
        a = AttendanceTotal.objects.get(student=self.student, course=self.course)
        return a.attendance


class Marks(models.Model):
    studentcourse = models.ForeignKey(StudentCourse, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, choices=test_name, default='Class Test 1')
    marks1 = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])

    class Meta:
        unique_together = (('studentcourse', 'name'),)

    @property
    def total_marks(self):
        if self.name == 'End Semester Exam':
            return 100
        return 20


class MarksClass(models.Model):
    assign = models.ForeignKey(Assign, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, choices=test_name, default='Class Test 1')
    status = models.BooleanField(default='False')

    class Meta:
        unique_together = (('assign', 'name'),)

    @property
    def total_marks(self):
        if self.name == 'End Semester Exam':
            return 100
        return 20


class AttendanceRange(models.Model):
    start_date = models.DateField()
    end_date = models.DateField()


# Triggers


def daterange(start_date, end_date):
    for n in range(int((end_date - start_date).days)):
        yield start_date + timedelta(n)


days = {
    'Monday': 1,
    'Tuesday': 2,
    'Wednesday': 3,
    'Thursday': 4,
    'Friday': 5,
    'Saturday': 6,
}


def create_attendance(sender, instance, **kwargs):
    if kwargs['created']:
        start_date = AttendanceRange.objects.all()[:1].get().start_date
        end_date = AttendanceRange.objects.all()[:1].get().end_date
        for single_date in daterange(start_date, end_date):
            if single_date.isoweekday() == days[instance.day]:
                try:
                    AttendanceClass.objects.get(date=single_date.strftime("%Y-%m-%d"), assign=instance.assign)
                except AttendanceClass.DoesNotExist:
                    a = AttendanceClass(date=single_date.strftime("%Y-%m-%d"), assign=instance.assign)
                    a.save()


def create_marks(sender, instance, **kwargs):
    if kwargs['created']:
        if hasattr(instance, 'name'):
            ass_list = instance.class_id.assign_set.all()
            for ass in ass_list:
                try:
                    StudentCourse.objects.get(student=instance, course=ass.course)
                except StudentCourse.DoesNotExist:

College-ERP-master/info/forms.py
# forms.py
from django import forms

class ToggleForm(forms.Form):
    checkbox = forms.BooleanField(label='Toggle', required=False)

College-ERP-master/info/templates/info/add_HOD.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>homepage</title>
      {% load static %}

    <!-- Bootstrap core CSS -->
      <link href="{% static '/info/homepage/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Custom styles for this template -->
      <!-- <link href="{% static '/info/homepage/css/heroic-features.css' %}" rel="stylesheet"> -->
          <!-- <link href="{% static '/info/bootstrap/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css"> -->
          <link href="{% static '/info/homepage/css/nav_bar.css' %}" rel="stylesheet">
      <style>
        .toggle {
         position: relative;
         display: block;
         width: 150px;
         height: 40px;
         padding: 3px;
         margin-left: 25%;
         border-radius: 50px;
         cursor: pointer;
      }
      .toggle-input {
         position: absolute;
         top: 0;
         left: 0;
         opacity: 0;
      }
      .toggle-label {
         position: relative;
         display: block;
         height: inherit;
         font-size: 100%;
         background: red;
         border-radius: inherit;
         box-shadow: inset 0 1px 2px rgba(0, 0, 0, 0.12), inset 0 0 3px
         rgba(0, 0, 0, 0.15);
      }
      .toggle-label:before,
      .toggle-label:after {
         position: absolute;
         top: 50%;
         color: black;
         margin-top: -.5em;
         line-height: 1;
      }
      .toggle-label:before {
         content: attr(data-off);
         right: 11px;
         color: #fff;
         text-shadow: 0 1px rgba(255, 255, 255, 0.5);
      }
      .toggle-label:after {
         content: attr(data-on);
         left: 11px;
         color: #fff;
         text-shadow: 0 1px rgba(0, 0, 0, 0.2);
         opacity: 0;
      }
      .toggle-input:checked~.toggle-label {
         background: green;
      }
      .toggle-input:checked~.toggle-label:before {
         opacity: 0;
      }
      .toggle-input:checked~.toggle-label:after {
         opacity: 1;
      }
      .toggle-handle {
         position: absolute;
         top: 4px;
         left: 4px;
         width: 38px;
         height: 38px;
         background: linear-gradient(to bottom, #FFFFFF 40%, #f0f0f0);
         border-radius: 50%;
      }
      .toggle-handle:before {
         position: absolute;
         top: 50%;
         left: 50%;
         margin: -6px 0 0 -6px;
         width: 16px;
         height: 16px;
      }
      .toggle-input:checked~.toggle-handle {
         left: 72%;
         box-shadow: -1px 1px 5px rgba(0, 0, 0, 0.2);
      }

      /* Transition*/
      .toggle-label,
      .toggle-handle {
         transition: All 0.3s ease;
         -webkit-transition: All 0.3s ease;
         -moz-transition: All 0.3s ease;
         -o-transition: All 0.3s ease;
      }
      .form-group{
        padding: 5%;
      }
      
      </style>

  </head>

  <body>

    
    <header>
      <link href="{% static '/info/homepage/css/chatbox.css' %}" rel="stylesheet">
    
    <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a href="{% url 'index' %}">Home</a>
        <a href="{% url 'announcement_page'%}">Announcements</a>
        <div class="dropdown">
        <a href="{% url 'edit_members'%}" class="dropbtn">Manage members</a>
        <div class="dropdown-content">
            <a href="{% url 'add_teacher' %}">Add Staff</a>
            <a href="{% url 'add_student' %}">Add Students</a>
            <a href="{% url 'assign_teacher' %}">Allocate/Deallocate Teachers</a>
            <a href="{% url 'add_delete_dept' %}">Add/Delete Department</a>
            <a href="{% url 'add_delete_class' %}">Add/Delete Class</a>
        </div>
    </div>
        <a href="#" data-toggle="modal" data-target="#logoutModal">Logout</a>
      </div>
      
      <!-- Use any element to open the sidenav -->
      <span onclick="openNav()" style="cursor: pointer;">
        <div class="containers">
            <div class="bar1"></div>
            <div class="bar2"></div>
            <div class="bar3"></div>
          </div>
    
    </span>
    <h1>Welcome {{ request.user }}</h1>
    <script>
      /* Set the width of the side navigation to 250px */
      function openNav() {
      document.getElementById("mySidenav").style.width = "250px";
      }

      /* Set the width of the side navigation to 0 */
      function closeNav() {
      document.getElementById("mySidenav").style.width = "0";
      }

      function myFunction(x) {
      x.classList.toggle("change");
      }
    </script>
  </header>
    <!-- Page Content -->
    <div class="container">

      <!-- Jumbotron Header -->
      

      <!-- Page Features -->
      
      <div class="row text-center justify-content-center">
        <div class="row justify-content-center">
            <div class="">
              <span class="anchor" id="formUserEdit"></span>
              <hr class="my-5">
              <div class="card card-outline-secondary" style="min-width: 500px; flex: none;">
                <div class="card-header" id="Toggle_button">
                  <h2>Edit HOD</h2>
                </div>
                <div class="card-body">
                  <form class="form" role="form" method="POST" action="{% url 'add_delete_HOD' %}">
                        {% csrf_token %}
                        <div class="form-group row">
                            <label class="col-lg-3 col-form-label form-control-label">Department</label>
                            <div class="col-lg-9">
                                <select class="form-control" name="dept" id="depts" required>
                                  <option value="---">---</option>
                                    {% for dept in all_dept %}
                                        <option value="{{ dept.id }}">
                                            {{ dept }}
                                        </option>
                                    {% endfor %}
                            </select>
                            </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-lg-3 col-form-label form-control-label">New HOD</label>
                                <div class="col-lg-9">
                                    <select class="form-control" name="f_names" id="f_name" required>
                                        
                                </select>
                                </div>
                                </div>
                                
                        </div>
 


                    <div class="form-group row justify-content-left">
                        <div class="ml-auto mr-3" >
                            <a class="btn btn-danger" href="{% url 'index' %}"> Cancel </a>
                            <input class="btn btn-secondary ml-auto" type="button" id="v_HOD" value="View HOD"> 
                            <input class="btn btn-secondary ml-auto" type="reset" value="Reset"> 
                            <input class="btn btn-primary ml-auto" type="submit" value="Submit">
                        </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        
      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
            <a class="btn btn-primary" href="/accounts/logout">Logout</a>
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript -->


      <script src="{% static '/info/homepage/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static '/info/homepage/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>




    <script>
      /* Set the width of the side navigation to 250px */
      function openNav() {
      document.getElementById("mySidenav").style.width = "250px";
      }

      /* Set the width of the side navigation to 0 */
      function closeNav() {
      document.getElementById("mySidenav").style.width = "0";
      }

      function myFunction(x) {
x.classList.toggle("change");
}
    </script>

<script>
    const departmentDropdown = document.getElementById('depts');
const faculty_names = document.getElementById('f_name');
const class_dropdown = document.getElementById('classes_list');
const subjects_dropdown = document.getElementById('subjects');
const slots_time = document.getElementById('slots');
const view_hod = document.getElementById('v_HOD');

view_hod.addEventListener('click',()=>{
  console.log("Hod View Started");
  
var newtab = window.open("", "anotherWindow", "width=600,height=400");  
var html = "<style>tr:hover {background-color: #D6EEEE;}tr:nth-child(even) {background-color: rgba(150, 212, 212, 0.4);}th:nth-child(even),td:nth-child(even) {background-color: rgba(150, 212, 212, 0.4);}table td,th:first-child {border-left: none;}table td,th:last-child {border-right: none;}table td,th {border-left: 1px solid #000;border-right: 1px solid #000;} .centers {border-style:solid; margin-left: auto;margin-right: auto;}</style><table class="+"centers"+"><tr><th>ID</th><th>HOD Name</th><th>Department</th>";
  fetch(`/get_hods`)
            .then(response => response.json())
            .then(hod => {
                // Populate the subject dropdown with fetched subjects
                console.log(hod.length)
                for (var i = 0; i < hod.length; i++) {
                  // for (var j = 0; j < hod[i].length; j++) {
                    html+="<tr>";
                    html+="<td>"+hod[i][0]+"</td>";
                    html+="<td>"+hod[i][1]+"</td>";
                    html+="<td>"+hod[i][2]+"</td>";
                    html+="</tr>";
                  // }
                }
                console.log(html)
                newtab.document.write(html);
          })
            .catch(error => console.error('Error fetching faculty:', error));

});

departmentDropdown.addEventListener('change', () => {
    const selectedDepartmentId = departmentDropdown.value;
    // Clear the current options in the subject dropdown
    faculty_names.innerHTML = '';
    
    // Fetch subjects based on the selected department
    fetch(`/get_d_teachers/${selectedDepartmentId}/`)
        .then(response => response.json())
        .then(subjects => {
            // Populate the subject dropdown with fetched subjects
            subjects.forEach(subject => {
                const option = document.createElement('option');
                option.value = subject.id;
                option.textContent = subject.name;
                faculty_names.appendChild(option);
            });
        })
        .catch(error => console.error('Error fetching faculty:', error));

});

</script>



  </body>

</html>

College-ERP-master/info/templates/info/presentation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Presentation</title>
</head>
<body>
    <!-- Decktopus Presentation --><div style="position: relative; padding-top: 56.25%; overflow: hidden"><iframe allowfullscreen src="https://decktop.us/4V-w2CFyr?embedded=true" style="position: absolute; top: 0; left: 0; width: 100%; height:100%; border:none"></iframe></div>
</body>
</html>

College-ERP-master/info/templates/info/t_attendance.html
{% extends 'info/base.html' %}
{% block content %}
{% if c.student_set.all %}

<form action="{% url 'confirm' assc.id %}" method="post">
            {% csrf_token %}
    <div class="card mb-3">
        <div class="card-header">
          <i class="fas fa-table"></i>
         <b>{{ dept1.name }}</b></div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                    <th>Student name</th>
                    <th></th>
                </tr>
              </thead>
                <tbody>
                {% for s in c.student_set.all %}
                    <tr>
                    <td>{{s.name}}</td>
                    <td>
                        <div class="btn-group btn-group-toggle" data-toggle="buttons">

                                <label class="btn btn-outline-success active">
                                    <input type="radio" name="{{ s.USN }}" id="option1" autocomplete="off" value="present" checked> Present
                                </label>

                                <label class="btn btn-outline-danger">
                                    <input type="radio" name="{{ s.USN }}" id="option2" autocomplete="off" value="absent"> Absent
                                </label>
                        </div>
                    </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
          </div>
        </div>
      </div>


    <input class="btn btn-success" type="submit" value="Submit">
</form>


{% else %}
    <p>No students in Class</p>
{% endif %}

{% endblock %}

College-ERP-master/info/templates/info/t_extra_class.html
{% extends 'info/base.html' %}
{% block content %}
{% if c.student_set.all %}

<form action="{% url 'e_confirm' ass.id %}" method="post">
            {% csrf_token %}
    <label for="date">Enter Date: </label>
    <input type="date" name="date">


    <div class="card mb-3">
        <div class="card-header">
          <i class="fas fa-table"></i>
         <b>{{ dept1.name }}</b></div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                    <th>Student name</th>
                    <th></th>
                </tr>
              </thead>
                <tbody>
                {% for s in c.student_set.all %}
                    <tr>
                    <td>{{s.name}}</td>
                    <td>
                        <div class="btn-group btn-group-toggle" data-toggle="buttons">

                                <label class="btn btn-outline-success active">
                                    <input type="radio" name="{{ s.USN }}" id="option1" autocomplete="off" value="present" checked> Present
                                </label>

                                <label class="btn btn-outline-danger">
                                    <input type="radio" name="{{ s.USN }}" id="option2" autocomplete="off" value="absent"> Absent
                                </label>
                        </div>
                    </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
          </div>
        </div>
      </div>


    <input class="btn btn-success" type="submit" value="Submit">
</form>


{% else %}
    <p>No students in Class</p>
{% endif %}

{% endblock %}